services:
  postgres:
    image: postgres:15
    container_name: wikhistory-db
    environment:
      POSTGRES_USER: history_user
      POSTGRES_PASSWORD: history_pass
      POSTGRES_DB: wikhistory_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: